### ISSUE TITLE
Theme has been broken since Atom 0.166.0

### ISSUE THREAD

**Issue by usami** [irrationalistic/atom-tasks#12]
First, thanks for this awesome package! I've totally switched to manage todo list on Atom.

Since version 0.166.0, the Atom text editor uses shadow DOM by default, and looks it breaks the tasks' theme.

This is how current todo list looks like:
![screen shot 2015-01-09 at 3 52 24 pm](https://cloud.githubusercontent.com/assets/670769/5687168/a31850ae-9817-11e4-8a9e-e69b7571cb44.png)

And after disabling shadow DOW in setting, I can see the original look:
![screen shot 2015-01-09 at 3 51 31 pm](https://cloud.githubusercontent.com/assets/670769/5687177/c4f9dfee-9817-11e4-8293-177447c18767.png)

**Comment by irrationalistic** [comment]
Thanks for the comment!

I'm currently looking into this. I've narrowed it down to an issue with the shadow dom. Since this package requires some awkward re-generation of the syntax files on-load, it seems that the theme styles aren't being applied into the shadow dom.

Quick fix is to just disable the shadow dom option in the editor settings!

**Comment by irrationalistic** [comment]
I've opened up a discussion thread on atom.io: https://discuss.atom.io/t/shadowdom-breaks-dynamic-grammar/14191
