### ISSUE TITLE
Please add something similar to TaskPaper query language

### ISSUE THREAD

**Issue by kirillsalykin** [irrationalistic/atom-tasks#19]
Hi,
i found the query language mentioned here: http://www.macdrifter.com/2014/02/the-taskpaper-rd-notebook.html.

UPD: http://imissmymac.com/wp-content/uploads/2013/02/TaskPaper-Users-Guide.pdf

Example: "not @done and not @cancel and not @hold and (@started or @draft or @waiting or @today)"

Also, being able to manage these queries is important too. (save/edit/delete).

Thanks!

**Comment by irrationalistic** [comment]
I'll have to do a bit of research into how this can be handled in Atom. Since it is a text editor and this is a text format, it might be difficult to "remove" lines visually without deleting them from the buffer. This could be an issue because if the user saves the file without the lines showing, they will actually be removed from the output. Would it be acceptable if the queries were treated like find, by showing a new tab?

**Comment by kirillsalykin** [comment]
> Would it be acceptable if the queries were treated like find, by showing a new tab?
yes, totally. I guess it is the only option.

Also, what do you think about making more TaskPaper compatible? There are some mobile apps that understands this format.

1. Display done/not done status based on @done tag. But we should not include the symbol into text, eg not save 'checked' with text. (Maybe display it i gutter?)
2. Support also '. taskpaper' extension.

Please look. Is possible? Should i create separate story for this? Also i can help with changes.

**Comment by irrationalistic** [comment]
Could you make separate issues for those items?

Also, for some clarity, with number 1. Do you mean removing the check mark? I would rather not do that since it's pretty integral to the current system, but I do have some other requests that will require a pretty hefty rewrite of some code and I could add your request to the considerations! If you can put them in separate issues, that'd be great. Then we can keep them all in different threads. Thanks!

**Comment by irrationalistic** [comment]
For the query language, we are a bit limited in terms of the power of the editor meaning that I can't show/hide separate lines. For this version you'd have to just use the "find" system and show the results in a different window with completely different functionality. I'm experimenting with an alternative version where I handle the page rendering instead of the default text editor. This gives me more control over what's displayed and what's not, but it also may mean less default behaviors like having vim-mode enabled. I'll keep testing though!

**Comment by mandel01** [comment]
First, thanks for the great Atom package! I have been using it for a couple days and really enjoy it. Moving the `@done` items to the bottom is a fantastic feature.

The one thing really missing is the ability to focus on specific items (either by start/due date or by importance or other tag). I'll typically have 60-80 items in my list, but I need to select the next 3 to work on. That is difficult if scanning a large list, but if a subset were presented (in another tab, popup, or in any interface really) then I could select among those.

All three of the current reported issues address the problem of paring down one's list in different ways, but this issue report resonated most for me. Here were some other resources I found in case they can be of use. I'm sorry I don't know CoffeeScript but happy to research items if I can be helpful at all.

Clever filtering:
http://imissmymac.com/hide-future-start-dates-in-taskpaper/

Command line option with Python scripting. This would solve it for me, actually. I couldn't get this to work on my system but I think that has to do with my Python installation. Still troubleshooting it...
https://github.com/bevesce/TodoFlow/blob/master/README.md

**Comment by irrationalistic** [comment]
Thanks @mandel01!

I definitely am seeing the need for being able to control the listing. It's difficult because I have to weigh the two sides of the coin here: On one side, I use the native text editor but it becomes impossible to customize the list with non-text-based operations (no show/hide, toggle, focus, etc). On the other side, I would have to custom code my own view system to supersede that of the normal text editor, but the cons here are that you'd lose normal text editor utility (such as, with vim-mode, being able to select a series of items and complete them using key commands only). I could certainly start to build back up that functionality, but then i'm emulating native behavior!

I need to devote a bit more time to the alternate branch I have for building an entirely custom UI. Once that's at a point where it is usable, I'd probably want to test it a bit to make sure it's actually viable.

Thanks all for your thoughts! Keep them coming, it's great to have your perspectives :)

**Comment by stephenll** [comment]
I am very new to Atom and was hoping for similar functionality with this package.  Would it be possible to accomplish this with Folding?  I can manually select lines and fold them.  Another thought: The author of TaskPaper has a JS library for interfacing with taskpaper files. Could you utilize that in this package?

**Comment by irrationalistic** [comment]
The root of the problem is just that the user experience for the result list isn't fully decided yet. We could certainly add in a new pane that shows results much like the native search, but that would already be supported. Code folding could help, but it won't really look or function the way it would be expected (too much magic and fragility).

The ideal solution would be to create a custom file renderer for tasks files that would extend from the capabilities of the normal text editor, but allow for things like filtering and custom line styles. Then the challenge there is to include similar functionality that plain text gets you like integration with vim-mode!

**Comment by gstrout** [comment]
Has there been any progress on this request? 

I have little-to-no programming skill, so I con't contribute directly, but the addition of that feature would make Atom.io much more valuable to me. 

I am using the Tasks package addon as a Taskpaper todo-list management option on a windows machine (which Taskpaper doesn't provide a native app), but the Search function is super key to navigating a large list of taskpaper formatted lists and, so far, I don't see a way to handle this.

**Comment by irrationalistic** [comment]
@gstrout Unfortunately no :) I haven't really had the time to work on the new rendering system! I definitely agree that this would bring the task management system in Atom to the next level for sure. Hopefully I will have time soon.
