### ISSUE TITLE
Where can I find more thorough setup/use documentation?

### ISSUE THREAD

**Issue by mlabita37** [irrationalistic/atom-tasks#57]
Hi,

I've never used a task manager in an editor before. Should I follow the documentation for Sublime's Plain Tasks to get setup and start using? Sorry, not much to go on in the provided documentation.

Thanks!

**Comment by irrationalistic** [comment]
Good question!

For the most part, the readme covers functionality, so creating "projects" by ending a line with `:` and then creating tasks under that project using the hotkeys. It's a pretty straightforward system since there's really just formatting and hotkeys as it's all plain text.

Did you have any specific questions in regards to getting set up?

**Comment by irrationalistic** [comment]
Closing this for now! Feel free to re-open if you need more documentation or feel something is missing :)
