### ISSUE TITLE
Open URL

### ISSUE THREAD

**Issue by dinesh-v** [irrationalistic/atom-tasks#73]
Open URL using shortcut feature is needed.

`⌘ + shift + u` will open the url under the cursor in your default browser, other than http(s) schemes must be enclosed within <>, e.g. <skype:nickname>

**Comment by irrationalistic** [comment]
Does this package handle your use-case?
https://atom.io/packages/link

**Comment by dinesh-v** [comment]
@irrationalistic Thanks for pointing out the package. It doesn't work on mac.

**Comment by irrationalistic** [comment]
@dinesh-v: I have both Tasks and Link packages installed on mac. I created a new task item and typed out a link. Hitting the Link plugin's default keybinding, ctrl+shift+o, does open that link when my cursor is on it! Give it a try :) Closing this task for now since i believe it covers the use case, feel free to re-open if not!

**Comment by dinesh-v** [comment]
@irrationalistic It worked when I didn't hover cursor upon the link.
